### ISSUE TITLE
Error: Input required and not supplied: repo-token

### ISSUE THREAD

**Issue by ajaydwarkani** [pozil/auto-assign-issue#116]
Hi,

I have setup an auto PR assignment and get the below error. Unable to figure out why it's not working. The similar code is working fine for auto assigning the issues but failing for PR assignment.

```
  with:
    teams: team-internal
    abortIfPreviousAssignees: false
    removePreviousAssignees: false
    allowNoAssignees: false
    allowSelfAssign: true
Error: Input required and not supplied: repo-token
```

here is the configuration of the yaml file

```
name: PR assignment

on:
  pull_request:
    types: [opened, reopened]
    
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
        issues: write    
    steps:
      - name: 'Auto-assign PR'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.ASSIGN_ISSUE_TOKEN }}
          teams: team-internal
```
