### ISSUE TITLE
Issue with repo-token

### ISSUE THREAD

**Issue by ItsGiantCookie** [pozil/auto-assign-issue#127]
Hi, I'm new to using Personal Access Tokens and Secrets and I'm having some issues with using my Personal Access Token in my Org.
It is a fine-grained token, it's set as active in the Org itself and has the permission 'members' with read permission, which according to the short text, should give access to the Orgs teams and members info.

![image](https://github.com/pozil/auto-assign-issue/assets/79613232/98d3d9a2-9b94-45bb-8f52-1a24f8ed5b64)

Is there a specific way to put a PAT into a Org-Secret to make it work?

This is the code I used.
```
name: PR and Issue assignment

on:
    issues:
      types: [opened]

    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: 'Auto-assign PR and Issues'
              uses: pozil/auto-assign-issue@v2
              with:
                  repo-token: ${{ secrets.GR_MM_TOKEN_LOCAL }}
                  teams: scripting
                  numOfAssignee: 1
```
