### ISSUE TITLE
[Bug]: Can't find private repository name

### ISSUE THREAD

**Issue by ElPrudi** [pozil/auto-assign-issue#168]
I'm working in a team that has a private github repository. We keep track of issues by using the issue tab. Sadly, this action can't find private repositories.

This is my action:

```yaml
name: Auto Assign Maintainer
on:
  issues:
    types: [opened]

jobs:
  assign-maintainer:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Assign issue to maintainers
        uses: pozil/auto-assign-issue@v2
        with:
          assignees: ${{ github.repository_owner }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```
